nomePlaca = {
    'R-1': 'Parada obrigatória',
    'R-2': 'Dê a preferência',
    'R-3': 'Sentido proibido',
    'R-4A': 'Proibido virar à esquerda',
    'R-4B': 'Proibido virar à direita',
    'R-5A': 'Proibido retornar à esquerda',
    'R-5B': 'Proibido retornar à direita',
    'R-6A': 'Proibido estacionar',
    'R-6B': 'Estacionamento regulamentado',
    'R-6C': 'Proibido parar e estacionar',
    'R-7': 'Proibido ultrapassar',
    'R-8A': 'Proibido mudar de faixa ou pista de trânsito da esquerda para direita',
    'R-8B': 'Proibido mudar de faixa ou pista de trânsito da direita para esquerda',
    'R-9': 'Proibido trânsito de caminhões',
    'R-10': 'Proibido trânsito de veículos automotores',
    'R-11': 'Proibido trânsito de veículos de tração animal',
    'R-12': 'Proibido trânsito de bicicletas',
    'R-13': 'Proibido trânsito de tratores e máquinas de obras',
    'R-14': 'Peso bruto total máximo permitido',
    'R-15': 'Altura máxima permitida',
    'R-16': 'Largura máxima permitida',
    'R-17': 'Peso máximo permitido por eixo',
    'R-18': 'Comprimento máximo permitido',
    'R-19': 'Velocidade máxima permitida',
    'R-20': 'Proibido acionar buzina ou sinal sonoro',
    'R-21': 'Alfândega',
    'R-22': 'Uso obrigatório de corrente',
    'R-23': 'Conserve-se à direita',
    'R-24A': 'Sentido de circulação da via ou pista',
    'R-24B': 'Passagem obrigatória',
    'R-25A': 'Vire à esquerda',
    'R-25B': 'Vire à direita',
    'R-25C': 'Siga em frente ou à esquerda',
    'R-25D': 'Siga em frente ou à direita',
    'R-26': 'Siga em frente',
    'R-27': 'Ônibus, caminhões e veículos de grande porte, mantenham-se à direita',
    'R-28': 'Duplo sentido de circulação',
    'R-29': 'Proibido trânsito de pedestres',
    'R-30': 'Pedestre, ande pela esquerda',
    'R-31': 'Pedestre, ande pela direita',
    'R-32': 'Circulação exclusiva de ônibus',
    'R-33': 'Sentido de circulação na rotatória',
    'R-34': 'Circulação exclusiva de bicicletas',
    'R-35A': 'Ciclista, transite à esquerda',
    'R-35B': 'Ciclista, transite à direita',
    'R-36A': 'Ciclistas à esquerda, pedestres à direita',
    'R-36B': 'Pedestres à esquerda, ciclistas à direita',
    'R-37': 'Proibido trânsito de motocicletas, motonetas e ciclomotores',
    'R-38': 'Proibido trânsito de ônibus',
    'R-39': 'Circulação exclusiva de caminhão',
    'R-40': 'Trânsito proibido a carros de mão'}

if __name__ == '__main__':
    from colorama.ansi import Fore
    
    for k, i in nomePlaca.items():
        print(f'{Fore.GREEN+k}:{Fore.BLUE+i+Fore.RESET}')