text_char = '''
ashfçsafjasd
sfsdfads
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsd
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
fsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
fsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsd
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n
sdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\nsdfsd\n

'''